server:
  port: 8761

  # freemarker 配置
spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    # 配置热部署
  devtools:
    restart:
      enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


