server:
  port: 12345
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowed-headers: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            maxAge: 30
      routes:
        - id: user_module
          uri: lb://User
          predicates:
            - Path=/user/login

        - id: user_account
          uri: lb://UserAccount
          predicates:
            - Path=/code/**,/avatar/**,/user/**,/user/interests/**

        - id: news_sharing
          uri: lb://NewsSharing
          predicates:
            - Path=/news/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
