server:
  port: 12345
  max-http-request-header-size: 2000000
spring:
  application:
    name: gateway
  # 配置热部署
  devtools:
    restart:
      enabled: true
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowed-headers: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            maxAge: 30
      routes:
        - id: user_account
          uri: lb://UserAccount
          predicates:
            - Path=/code/**,/avatar/**,/user/**,/user/interests/**,/user/view/**

        - id: news_sharing
          uri: lb://NewsSharing
          predicates:
            - Path=/news/**,/newsImage/**,/newsMessage/**
        # 赛事管理
        - id: match_regulation
          uri: lb://MatchRegulation
          predicates:
            - Path=/match/**,/match/matchMessage/**,/signUp/**,/userAbility/**
        - id: tutorial_regulation
          uri: lb://TutorialRegulation
          predicates:
            - Path=/tutorial/**
        - id: comment_regulation
          uri: lb://CommentRegulation
          predicates:
            - Path=/comment/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
