server:
  port: 8888
spring:
  application:
    name: User
  # 配置热部署
  devtools:
    restart:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

