spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "1234"
    url: jdbc:mysql://localhost:3306/pingpang?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
server:
  port: 8888

mp:
  outputDir: D:\10.软件工程课程\软件工程大四上\毕业论文\pingpang_backend\src\main\java

# 只输出com.sun.util包下的error日志
logging:
  level:
    com.sun.util: debug


