server:
  port: 8070
spring:
  application:
    name: CommentRegulation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "1234"
    url: jdbc:mysql://localhost:3306/pingpang?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka